### ISSUE TITLE
Change AcceptGift function in baseclient

### ISSUE THREAD

**Issue by NGovani** [SOMAS2020/SOMAS2020#119]
Currently the AcceptGift function in the client allows the agent to change the recipient and offerer id, aswell as the amount offered. This would break the system if a malicious agent changed these values.

https://github.com/SOMAS2020/SOMAS2020/blob/a71dad4f23f4fe110a13bc3d13acdb7d7205e712/internal/common/baseclient/iito.go#L25-L36

**Comment by lhl2617** [comment]
@Darrekt taking over for now

**Comment by QFSW** [comment]
I don't think the client should be responsible for mutating or processing the gift offerings, they also shouldn't be able to see gifts that aren't offered to them. How I would imagine this to would

Introduce a `GiftOffer` struct. This just contains the amount, and the client offering that. Can also include the recipient but redundant

Introduce a `GiftResponse` struct. This contains the amount accepted, and the accepted/rejection reason

The server can still use `acceptedGifts` internally, its a decent way of representing it. `AcceptGifts` though should take (by value) a collection of `GiftOffers`. The client should then go and return a collection of `GiftResponse`s with its responses

The server is then responsible for mutating `acceptedGifts` internally based on the `GiftResponses`
Whoever picks this up let me know if you want to discuss this more, but I think this would be a cleaner way to do it that is simpler for the client and solves the "partial mutation" issue that the current system requires
