### ISSUE TITLE
`GameStateUpdate` usage

### ISSUE THREAD

**Issue by lhl2617** [SOMAS2020/SOMAS2020#122]
@preetl  suggested use of a mid-turn state update function `GameStateUpdate` in the server that is currently unused. This is actually quite vague because the client does not know at what point the function is called.

Each state-altering function should call their own individual function e.g. `ForageReturnUpdate` to update the resources. This makes it easier to program for clients

Thanks @mpardalos for raising this.

If no infra rep disagrees with this we will remove `GameStateUpdate`.

**Comment by lhl2617** [comment]
CC all infra reps -- @Darrekt @QFSW @JamesTev @Eirikalb  @Diregie-J @Neelesh99 @777jameskim @P-A-Ha

**Comment by QFSW** [comment]
Without a way for a client to have a sense of timing for the `GameStateUpdate` I agree it's probably not helpful, you could do your suggested way or the `GameStateUpdate` could come with an `Event` enum that could be `ForagingReturn` etc.

**Comment by lhl2617** [comment]
yeah we're doing a post-mortem in team 1 discord if you want to join @QFSW

**Comment by lhl2617** [comment]
#135 makes this function redundant. This will be removed.
