### ISSUE TITLE
`Resources` should be a custom type. We need to decide whether it is an int/uint/float64

### ISSUE THREAD

**Issue by lhl2617** [SOMAS2020/SOMAS2020#123]
Currently `Resources` is an `int`. We should make it a shared type like `Coordinate` etc.

The implementation of foraging seems to be using floats all around for resources. We should decide what type it should be.

I am on team int, but the current implementation is seemingly returning floats. Will this be rounded? Or should we use floats for resources?

**Comment by lhl2617** [comment]
thx @mpardalos for flagging

**Comment by JamesTev** [comment]
Quite firmly feel that we should use floats since the current design outputs real-valued utility values. Rounding or any other form of truncation would distort the input-output relationship. Will create custom types though.

**Comment by lhl2617** [comment]
Go ahead and make that change :) -- nod from me to make every reference to resource e.g. (CostOfLiving)

**Comment by lhl2617** [comment]
@mpardalos and I + team1 are going to attempt to connect some dots here, together with issue #122. will update.

**Comment by lhl2617** [comment]
@JamesTev  we're fixing it now because it won't work with partial changes

**Comment by JamesTev** [comment]
Ah okay - already pushed changes to `infra-feat-foraging` branch regarding this but was still in process of checking. But looks similar to what you've  done.

**Comment by lhl2617** [comment]
#128 partially fixes this. There are still references to int values for resources in #121

**Comment by lhl2617** [comment]
![image](https://user-images.githubusercontent.com/33488131/103112082-e0531e80-464a-11eb-9635-e469aa403a04.png)
