### ISSUE TITLE
Fix package-level globals in  IIGO

### ISSUE THREAD

**Issue by mpardalos** [SOMAS2020/SOMAS2020#125]
In [orchestration.go](https://github.com/SOMAS2020/SOMAS2020/blob/main/internal/server/iigointernal/orchestration.go), all state vars are package globals. These should *really* be in `gameState`. 

This was already raised in the review:
![image](https://user-images.githubusercontent.com/2512446/103038248-a9133d80-4576-11eb-9b83-c7aa80c1f7d2.png)

Just mentioning it, but it works, so if no one feels like fixing it, it's fine.

**Comment by Neelesh99** [comment]
PR #138 has a (sort of) fix for this. no one will be hunting for variables every again, its fed directly through signature.

**Comment by mpardalos** [comment]
The globals are still there, but they seem to be basically unused? I'm not sure if that is actually the case. Can we remove them?

**Comment by Neelesh99** [comment]
Not quite unused, they are used to keep persistence of certain variables (e.g. cumulative sanction values) across turns. We could technically move to gamestate, but I think that would be messier than the current implementation where these globals are only used by one function in the file that they are defined in.

**Comment by lhl2617** [comment]
#344 #346 #354 #360

**Comment by lhl2617** [comment]
#363 #362

**Comment by lhl2617** [comment]
resolved!
