### ISSUE TITLE
IIGO Tax Collection doesn't change the server gamestate

### ISSUE THREAD

**Issue by NGovani** [SOMAS2020/SOMAS2020#136]
https://github.com/SOMAS2020/SOMAS2020/blob/a71dad4f23f4fe110a13bc3d13acdb7d7205e712/internal/server/iigo.go#L19-L42

In the above code when the  resources are deducted from the newGameState that's only a copy of the server gamestate and thus the servers gamestate is never actually updated. This results in a discrepancy between what the amount of resources the server thinks the client has and what the client thinks they have. 

GameStateUpdate is also planned to be deprecated in #135  so should be removed and replaced with a function telling the client how much tax they paid.

The common pool is also being moved into the environment with PR #124, and so line 25 will need to be updated

**Comment by Neelesh99** [comment]
Resolved in PR #138, iigo.go line 69 ;)
