### ISSUE TITLE
[INFRA/CORE] Add `golintci-lint-action` to repo.

### ISSUE THREAD

**Issue by lhl2617** [SOMAS2020/SOMAS2020#15]
Add https://github.com/golangci/golangci-lint-action into the main repo.

**Comment by lhl2617** [comment]
@Darrekt  feel free to pick up

**Comment by QFSW** [comment]
Do we want this to raise a warning via comment or cause the PR to fail? i.e could the linter ever be "wrong"?

**Comment by lhl2617** [comment]
@QFSW 
![image](https://user-images.githubusercontent.com/33488131/100752241-44821a00-33e0-11eb-89bd-4a7a798300e0.png)
