### ISSUE TITLE
No notification of disaster

### ISSUE THREAD

**Issue by mpardalos** [SOMAS2020/SOMAS2020#154]
There is currently no update to the clients when a disaster happens. I understand that disasters have not been fully implemented yet, but we should probably add an event like `Client.DisasterHappened`.

**Comment by lhl2617** [comment]
I remember from convos with @yp717 that islands just the next turn to realise that their resources disappeared -- this signifies a disaster. Not sure if that is changed.

**Comment by JamesTev** [comment]
Have implemented a disaster notification method in the base client in PR #176
