### ISSUE TITLE
IIGOHistory has no turn mapping

### ISSUE THREAD

**Issue by lhl2617** [SOMAS2020/SOMAS2020#159]
Currently IIGOHistory is just a slice of all added stuff since the beginning of the game. There is no way to know what turn something was added.

In #148 @preetl proposed letting judiciary etc. access to `GameState` history. This is a good idea--we can clear that IIGO history slice every start of turn.

Wondering what your thoughts are. Having access to `GameState` history runs the risk of accidentally modifying history (unless we copy it every time...--I miss CPP)

**Comment by Neelesh99** [comment]
Yeah I agree, we will need to add turn logging to the IIGOHistory (scoped as part of post-MVP IIGO) and also I think we might need to maintain a mini-cache of it in IIGO for our Historic Justice model of sanctioning (post-MVP IIGO).

**Comment by lhl2617** [comment]
resolved by #241
