### ISSUE TITLE
[INFRA/CORE] Ban panic and die from being used within client code

### ISSUE THREAD

**Issue by QFSW** [SOMAS2020/SOMAS2020#18]
Clients using panic or die will cause the whole simulation to fail irrecoverably, hence this needs to be banned in the rules
Ideally, we could have a CI action for this, but that is lower priority

**Comment by lhl2617** [comment]
rules for infra/rules instead - sorry for confusion.

**Comment by lhl2617** [comment]
i can pick up editing rules.

**Comment by lhl2617** [comment]
we could regex the diff in an action to look for `panic([.*])` or `die([.*])`--but to be honest that's a bit high effort low return... leaving this for now.
