### ISSUE TITLE
IIFO determineConfidence uses 0.0 as total values

### ISSUE THREAD

**Issue by MikeIsMike** [SOMAS2020/SOMAS2020#206]
In internal/common/baseclient/iifo.go, inside function determineConfidence, the varianceSum(line 101 ish) is equal to (totalCoordinateX + totalCoordinateY + totalMagnitude + totalTurn)/numberDisasterPassed, where the 4 total values are all set to 0. 

I'm assuming they were meant to be totalDisaster.CoordinateX, totalDisaster.CoordinateY, totalDisaster.Magnitude and totalDisaster.Turn respectively?

**Comment by lhl2617** [comment]
cc blame author @Eirikalb ; PR #85 approver @lhl2617 

https://github.com/SOMAS2020/SOMAS2020/blob/6902390f5a7401a3b6d1ec9e36c54274eb990a86/internal/common/baseclient/iifo.go#L101

**Comment by lhl2617** [comment]
@MikeIsMike good eye -- this part is not used at all in the accumulation

![image](https://user-images.githubusercontent.com/33488131/103423596-62899880-4b9f-11eb-8204-378fa493df19.png)

**Comment by lhl2617** [comment]
assigned to @Eirikalb

**Comment by lhl2617** [comment]
took over as this was stale. see #245
