### ISSUE TITLE
[INFRA/CORE] (Nice to have) discord bot that notifies #infrastructure on merge?

### ISSUE THREAD

**Issue by lhl2617** [SOMAS2020/SOMAS2020#21]
low pri but really nice to have...

@QFSW  any ideas?

**Comment by QFSW** [comment]
Want anything else as notifications? it gives us quite a breadth of options. For now I've done (we can make a new channel or remove some of them if it gets too spammy)

 - new forks
 - issue updates
 - PR updates

**Comment by lhl2617** [comment]
I think a new `infrastructure-github` channel would be neat!

**Comment by QFSW** [comment]
Done. I want to make that channel readonly, but without removing the admin perm from `@everyone` that won't be possible
