### ISSUE TITLE
Add validation where client methods are called

### ISSUE THREAD

**Issue by mpardalos** [SOMAS2020/SOMAS2020#240]
I just had a bug in my client where I was accidentally returning `shared.ForageType(-1)` from my `ForageDecision()`. The error message was something about a nil pointer here: 

https://github.com/SOMAS2020/SOMAS2020/blob/7f0b3f62cdc911afeff6d387f2e595e7aea3a9fc/internal/server/forage.go#L41

I think we should add some validation to values returned by agent methods to make this kind of bug easier to understand. E.g. add checks for `nil` or enum values being outside the accepted range.

**Comment by JamesTev** [comment]
Thanks for raising this @mpardalos. Will check it out.
