### ISSUE TITLE
[IIGO] Rename GetTax to GetCommonPoolContribution

### ISSUE THREAD

**Issue by preetl** [SOMAS2020/SOMAS2020#249]
Tax/Contribution are causing confusion. The tax is a minimum contribution so it makes sense for this function to be called GetCommonPoolContribution. Just putting this here so we don't forget to do this after #208 is merged.

**Comment by lhl2617** [comment]
quite stale, any progress?

**Comment by preetl** [comment]
yeah I think i'll close this , doesn't seem worth changing a client side function name now
