### ISSUE TITLE
Foraging DeerHunt. Hunting negative deers.

### ISSUE THREAD

**Issue by E-Mac27** [SOMAS2020/SOMAS2020#252]
Hi!

I was messing about with the configs such that the foragingMaxDeerPerHunt == foragingDeerMaxPopulation (if you wish to reproduce this error). I was curious what would happen. 

It seems like agents are allowed to hunt negative deers? 

![image](https://user-images.githubusercontent.com/44125446/103483684-e1214880-4de0-11eb-8dae-63f5a7eacd55.png)
![image](https://user-images.githubusercontent.com/44125446/103483632-7d971b00-4de0-11eb-9ded-b79a1b7e9d8e.png)

**Comment by JamesTev** [comment]
Would you please try again with latest changes? May have fixed this behaviour

**Comment by E-Mac27** [comment]
We had a mini call to discuss this:
- Yes the most recent changes fixed this behaviour.
- MaxDeerPopulation is expected to be 2 or 3 times bigger than MaxDeerHunt for Deer Foraging to work properly.
- Placing MaxDeerPopulation == MaxDeerHunt breaks Deer Foraging such that all returns are 0. @JamesTev is looking into this.

**Comment by JamesTev** [comment]
Have figured out why - pMax and pCritical are equal if max deer per hunt and max population are equal so there will be a division by zero. Actually never considered this case because you'd never really want them equal but it definitely shouldn't break if you did for some reason. Will push a fix now - thanks for bringing this up @E-Mac27! 
```go
p := float64(population) / float64(dhConf.MaxDeerPerHunt)
alpha := (thetaMax - thetaCritical) / (pMax - float64(pCritical))

f1 := func(p float64) float64 { return thetaCritical * float64(p) }
f2 := func(p float64) float64 { return alpha*float64((p-pCritical)) + thetaCritical }
```
