### ISSUE TITLE
Is TaxTaken in Baseclient necessary?

### ISSUE THREAD

**Issue by preetl** [SOMAS2020/SOMAS2020#261]
@mpardalos it seems like this function is redundant as there is never a case when you would not pay the tax you intended to.

**Comment by mpardalos** [comment]
Completely agreed, should I remove it?

**Comment by NGovani** [comment]
There is one case where an agent doesn't properly note how many resources it has. However they should just check in getTaxContributions. So yeah it would make sense to remove

**Comment by preetl** [comment]
I've just PR'ed to remove it but thanks @mpardalos !

**Comment by preetl** [comment]
Solved in PR #268
