### ISSUE TITLE
[INFRA] Make certain params visible|selectively visible|always invisible to client

### ISSUE THREAD

**Issue by lhl2617** [SOMAS2020/SOMAS2020#263]

**Comment by lhl2617** [comment]
@JamesTev @NGovani @Eirikalb

**Comment by lhl2617** [comment]
Impl for client: selectively visible items are in a struct where there is a boolean flag saying whether it is visible for this round or not.

**Comment by lhl2617** [comment]
waiting for a list of params that falls under each of these three categories.

**Comment by Eirikalb** [comment]
Will discuss a bit further and will get back shortly

**Comment by lhl2617** [comment]
created #266 for this

**Comment by NGovani** [comment]
costOfLiving - Always Available 
minimumResourceThreshold - Always Available
maxCriticalConsecutiveTurns  - Always Available
disasterCommonpoolThreshold - Sometimes Available
disasterMagnitudeResourceMultiplier - Sometimes Available

**Comment by NGovani** [comment]
So these are the 5 initial ones, the rest of should never be shared

**Comment by NGovani** [comment]
There's also the ones that James is about to add those should probably all be - Sometimes Available

**Comment by lhl2617** [comment]
@JamesTev waiting for yours in foraging

**Comment by JamesTev** [comment]
Just opened #270. Relevant params would likely be `StochasticPeriod` (bool of whether or not disaster has stochastic period) and `Period` (actual or expected period between disasters)

**Comment by lhl2617** [comment]
ok, I think i'll  merge #266 first then we can do foraging in the future

**Comment by NGovani** [comment]
disasterMagnitudeResourceMultiplier - This should never be available, apologies i made a mistake as to its usage

**Comment by lhl2617** [comment]
closing. foraging stuff will be left to @JamesTev
