### ISSUE TITLE
[IIGO] add checks for rule proposal for if immutable rules are changed(not allowed), if rule variables fields are changed(not allowed)

### ISSUE THREAD

**Issue by MikeIsMike** [SOMAS2020/SOMAS2020#277]
Also read title please. Immutable rule check is already in place in modifyRule(), however modifyRule() is called in updateRule() which is after the proposal is voted on. Checks should perhaps be added in requestRuleProposal() (before the voting process).

**Comment by lhl2617** [comment]
any progress? @preetl @Neelesh99 could just close if feat. freeze prevents this.

**Comment by preetl** [comment]
Yea, i think it's a bit late now
