### ISSUE TITLE
[INFRA] `MaxTurns` and `MaxSeasons` default reduced to 10 from 100 

### ISSUE THREAD

**Issue by lhl2617** [SOMAS2020/SOMAS2020#296]
#227

**Comment by NGovani** [comment]
I assume it was 10 for testing reason to see if things worked. Setting it back to 100 would be ideal for basic simulations

**Comment by JamesTev** [comment]
Yeah my bad - was just for testing. Forgot to change back.

**Comment by JamesTev** [comment]
Should I submit a PR to revert or what?

**Comment by NGovani** [comment]
A PR would be great thanks!

**Comment by JamesTev** [comment]
#297
