### ISSUE TITLE
Epicentre not being calculated correctly

### ISSUE THREAD

**Issue by NGovani** [SOMAS2020/SOMAS2020#299]
There may be a potential issue with disasters not calculating the epicentre correctly. 
On the web version setting the disasterMagnitudeLambda to 10 and the disasterMagnitudeResourceMultiplier to 1,000,000 doesnt seem to affect the islands at all and it may be due to the epicentre being x: -1, y : -1. This is a snippet from the output
![image](https://user-images.githubusercontent.com/44064172/103802518-26df4a80-5047-11eb-994c-84fb0b6b4bcb.png)

**Comment by NGovani** [comment]
I realise now thats the default values, it seems instead the number is 0,0 for most disasters

**Comment by JamesTev** [comment]
Yeah basically just look at magnitude. If it's 0, the x, y coordinates aren't applicable.

**Comment by JamesTev** [comment]
MagLambda and multiplier also wouldn't affect that

**Comment by NGovani** [comment]
Yup apologies this one is on me completely read the data wrong
