### ISSUE TITLE
[INFRA/CORE] Action that prevents a team from editing another teams code

### ISSUE THREAD

**Issue by QFSW** [SOMAS2020/SOMAS2020#33]
Similar to issue #16 
When a team makes a PR, if there are any changes that are in other teams folders this should cause a failure
Naturally this only applies to fork PRs

Not sure how feasible this would be to do, but would be nice

**Comment by lhl2617** [comment]
an easier way to tackle is likely check if >1 of `.../clients/team{1-6}` folders are changed

**Comment by QFSW** [comment]
> an easier way to tackle is likely check if >1 of `.../clients/team{1-6}` folders are changed

Tried looking into this but can't find anything on making a trigger that needs >1/n conditions to be met

**Comment by lhl2617** [comment]
we just have to be really careful then.... 😢

**Comment by QFSW** [comment]
> we just have to be really careful then.... 😢

I think it could still be doable but really hacky and ugly, essentially you could do

```
if (fork == team_1_fork)
    trigger_team2_folder
    trigger_team3_folder
    ...

if (fork == team_2_fork)
    trigger_team1_folder
    trigger_team3_folder
    ...

...
```

And do that for all teams. Don't particularly want to do that though...

**Comment by lhl2617** [comment]
yeah let's just not

**Comment by QFSW** [comment]
Actually, it might not be that bad if I write a program to generate the trigger. I'll need everyone's forks before doing that though

**Comment by lhl2617** [comment]
you can look via the client folder commits. I noticed @mpardalos has his own fork for some reason!

**Comment by lhl2617** [comment]
Another way is to only allow PRs form forks with the title [TEAMx] then detect the team num from there? I'm not sure if there's a way to trigger from there, plus titles can be changed--might cause more problems

**Comment by lhl2617** [comment]
Or, labels on the PR. I think this is slightly more robust. For PRs from forks, a TEAMx label is required.

**Comment by lhl2617** [comment]
https://github.community/t/do-something-if-a-particular-label-is-set/17149

**Comment by lhl2617** [comment]
nah
