### ISSUE TITLE
[VIS] Enable tuning agents through params on Website

### ISSUE THREAD

**Issue by Eirikalb** [SOMAS2020/SOMAS2020#341]
Discussed this briefly with @yp717: Would it be possible to add a way to configure agents in the params file?

Some considerations:
    -  Option to run multiple instantiations of the same agent.
    -  Maybe dropdown menu where only the relevant params for that agent is showed
    -  Agent specific params should be able to be different to allow simulating different versions of the same agent in the same run

I know this is very late to mention but would be awesome to have this option to be able to tweak the agents live 💯

**Comment by lhl2617** [comment]
changing agents likely would be difficult, but let's go from the simple problem of mutating settings inside the initial state of the agent/parameters.

this would require some golang tweaking. you would need to add CLI flags to the code and figure a way to mutate these params in each client. 

the process:
1. add flags for the team requiring this
2. add a function in the client interface called "Configure" or similar taking in the parameters made by the flags
3. add a call to that Configure func in `func (s *SOMASServer) EntryPoint()` or `NewSOMASServer` for each client.

Each team would likely have different params and we'd end up hardcoding some stuff there, but this is honestly fine.

@Eirikalb this sounds good?

I cannot commit to picking this up however

**Comment by lhl2617** [comment]
from this point we might be able to do more complex stuff, but I doubt at the current timeframe it is possible from the vis. you might be better off running a local copy and uploading the `output.json` to vis.

**Comment by Eirikalb** [comment]
The procedure sounds very reasonable, and I think it should be easy to add this on a needs basis in each client if they want to be able to tweak their client. It would technically break baseclient, by adding the configure method which is less than ideal but I can make a PR on it tonight if I get the go ahead

**Comment by lhl2617** [comment]
yeah, there would need to be some hardcoding, Green light from me!

**Comment by lhl2617** [comment]
closing. inactive. tuning by sim team instead (@mpardalos _et al._)
