### ISSUE TITLE
Disaster prediction calculation issues

### ISSUE THREAD

**Issue by MikeIsMike** [SOMAS2020/SOMAS2020#377]
Correct me if I'm wrong on the following observations. 

https://github.com/SOMAS2020/SOMAS2020/blob/cef46aea1a1c649b0758a74e8641dab036373fc7/internal/common/baseclient/iifo.go#L84
On this line, should the Turn value be set to : `Turn:    uint(math.Floor(totalTurn/numberDisastersPassed)) - uint(totalTurn)%uint(numberDisastersPassed), // gives the number of turns left until the next disaster` ? Since this is for getting the mean prediction of the number of turns until the next disaster hits, so it makes sense for the value of `Turn` to decrement as the game goes from one turn to the next?

https://github.com/SOMAS2020/SOMAS2020/blob/cef46aea1a1c649b0758a74e8641dab036373fc7/internal/common/baseclient/iifo.go#L98
Not sure how the change above will affect the `Turn` confidence calculation here. In addition, the existing confidence calculation of `Turn` is a bit strange in that:
- `disaster.Turn` is within the range [0, the number of turns there has been since start of the game]
- `meanDisaster.Turn` is within the range [0, avg number of turns per disaster]

@Eirikalb ? @lhl2617

**Comment by lhl2617** [comment]
Assigning to blame author @Eirikalb

**Comment by lhl2617** [comment]
closing this -- stale. client should override if requirec correct feature. @MikeIsMike feel free to reopen and pr
