### ISSUE TITLE
Team 2 Client asking for negative allocation

### ISSUE THREAD

**Issue by Neelesh99** [SOMAS2020/SOMAS2020#383]
![Screenshot 2021-01-10 173309](https://user-images.githubusercontent.com/45288390/104130964-961cad80-536b-11eb-82fa-d66db7500e5d.png)

@lhl2617 put a new guard into allocations in #380 to prevent negative values being taken from common pool. This has resulted in any negative allocations causing program crash. @Eirikalb or any Team 2 peeps, could you pls have a look?

(Default main params btw)

**Comment by Eirikalb** [comment]
Pr with fix coming soon sorry!!!

**Comment by Eirikalb** [comment]
Should be fixed. Crossing fingers
