### ISSUE TITLE
[VIS] Different Visualisation between new run and CI Output

### ISSUE THREAD

**Issue by ramon15749** [SOMAS2020/SOMAS2020#406]
https://user-images.githubusercontent.com/35395504/104224610-24ad2f80-543d-11eb-953b-ab49c202b7c2.mp4

Different visualisations are shown on the CI Output page and on the New Run page

Also, downloading outputs from CI output and from New Run results in different file

**Comment by E-Mac27** [comment]
Ah. That might be because of Team 1 Agent. _I think_

**Comment by ramon15749** [comment]
@E-Mac27 yeah, I realised. Turns out the problem was something else as well (the CI Output and New Run giving me different graphs which I thought was the IIGO Payments problem but turns out it affects everyone. Sorry for the confusion

**Comment by tharusha-a** [comment]
The issue is that you are an idiot :) (jk)

**Comment by ramon15749** [comment]
@tharuraht oi r00d, you didnt know what CI stood for either
