### ISSUE TITLE
Some agents has put same people in the ballot multiple times

### ISSUE THREAD

**Issue by ramon15749** [SOMAS2020/SOMAS2020#439]
Some agents (Team3, Team4 and Team6 (might be others but this is what I found)) has put the same people in the ballot multiple times.

![image](https://user-images.githubusercontent.com/35395504/104504470-66bfa800-55da-11eb-91b6-32d27cdcdf4a.png)

[error.zip](https://github.com/SOMAS2020/SOMAS2020/files/5810835/error.zip)

**Comment by ramon15749** [comment]
[output.zip](https://github.com/SOMAS2020/SOMAS2020/files/5810513/output.zip)

**Comment by preetl** [comment]
Team 3 has fixed this issue (for our team)! With thanks to @Neelesh99 and @ramon15749

**Comment by Ning-72** [comment]
Sorry, I think it's fixed now #440
