### ISSUE TITLE
[INFRA/CORE] Auto-PR all forks with updates when main is updated

### ISSUE THREAD

**Issue by Darrekt** [SOMAS2020/SOMAS2020#49]
Currently, individual fork maintainers (presumably the infra reps) have to manually make a PR from main into their forks whenever it is updated. We would like to have an automatic PR to all forks of the project whenever a new changes are safely committed into main.

**Comment by Darrekt** [comment]
I've found something that may be worth a further read...I'll look into it later. I'm going to focus on catching up with the codebase first.

https://stackoverflow.com/questions/23793062/can-forks-be-synced-automatically-in-github

**Comment by Darrekt** [comment]
All teams can accomplish this by installing the following app on their forked repos:

https://github.com/wei/pull

That resolves the issue, closing.

**Comment by lhl2617** [comment]
lit. thx for this
